stages:
  flats_preprocessing:
    cmd: python src/flats_preprocessing.py
    deps:
    - data/raw/flats.csv
    outs:
    - prepared_data/flats_cleaned.csv
  house_preprocessing:
    cmd: python src/house_preprocessing.py
    deps:
    - data/raw/houses.csv
    outs:
    - prepared_data/houses_cleaned.csv
  merging_house_flats:
    cmd: python src/merging_house_flats.py
    deps:
    - prepared_data/flats_cleaned.csv
    - prepared_data/houses_cleaned.csv
    outs:
    - prepared_data/gurgaon_properties_merged.csv
  data_prepro_l2:
    cmd: python src/data_prepro_l2.py
    deps:
    - prepared_data/gurgaon_properties_merged.csv
    outs:
    - prepared_data/gurgaon_properties_cleaned_v1.csv
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - prepared_data/gurgaon_properties_cleaned_v1.csv
    outs:
    - prepared_data/gurgaon_properties_cleaned_v2.csv
  outlier_handling:
    cmd: python src/outlier_handling.py
    deps:
    - prepared_data/gurgaon_properties_cleaned_v2.csv
    outs:
    - prepared_data/outliers_cleaned.csv
  missing_value_imputation:
    cmd: python src/missing_value_imputation.py
    deps:
    - prepared_data/outliers_cleaned.csv
    outs:
    - prepared_data/missing_value_imputed.csv
  feature_selection:
    cmd: python src/feature_selection.py
    deps:
    - prepared_data/missing_value_imputed.csv
    outs:
    - prepared_data/gurgaon_properties_post_feature_selection.csv
